services:
  - docker

before_install:
  - docker build -t radicale .
  - docker run -d --name radicale -p 127.0.0.1:5232:5232 radicale

script:
  - docker ps | grep -q radicale
  - sleep 10
  - curl -sSL http://127.0.0.1:5232 | grep -q "Login"
