services: docker

language: python

python:
  - '3.6'

addons:
  apt:
    packages:
      - docker-ce

install:
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
  - pip install pipenv
  - pipenv sync --dev

script:
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv check
  - pipenv run pytest -v

deploy:
  # Deploy tag
  - provider: script
    on:
      tags: true
    script: ci/build-push.sh
    skip_cleanup: true
  # Deploy latest
  - provider: script
    on:
      branch: master
    script: ci/build-push.sh
    skip_cleanup: true
